### ISSUE TITLE
Watch later feature

### ISSUE THREAD

**Issue by karlo2105** [azzy9/plugin.video.lbryplus#4]
Thanks for having integrated Odysee into Lbry addon. Could you please add watch later feature within Odysee settings ?

**Comment by azzy9** [comment]
Hi @karlo2105,
I have started to add a simple live stream section in the addon, which needs to be improved upon.
I have had a quick look how the watch later feature is used on the site and does look plausible to implement, but I am not 100% sure the best way to implement this. But I guess I will just try and add it and see how it turns out.

Just a note for myself, this is done via the https://api.na-backend.odysee.com/api/v1/proxy?m=preference_set endpoint.

**Comment by azzy9** [comment]
V0.5.0 should now allow you to get/add/delete from your watch later list.
The live stream only get the URL and pass it on to Kodi, which then gets the actual live stream.
I found enabling the HTTP only setting in the debug section seems to make videos and stream smoother.
